# Generated by Django 5.0.3 on 2024-03-09 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='return_date',
        ),
    ]
