# Generated by Django 5.0.3 on 2024-03-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_tickets_return_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
